# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 8.10.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定网站源码分支，因人而异。hexo网站源码托管在独立repo则不用设置此项
branches:
  only:
    - master 

before_script: .travis/setup.sh
script: .travis/build.sh

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
# End: Build LifeCycle
