# 该文件是 Jekyll 的站点配置
#
# 这些配置可通过 {{ site.XXX }} 访问
# 注意：本文件不在 bundle exec jekyll serve 的自动更新之列

# ==== 目录结构设置 ====

source:      ./src
destination: ./dist
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data

# 分类
collections: 
  drafts:
    output: false
  posts:
    output: true
    permalink: /p/:year-:month-:slug/
  raw:
    output: true
    permalink: /:slug/

# ==== 渲染相关设置/变量 ===

title: 开源社
email: your-email@example.com
description: 开源社致力于推动中国开源社区成为全球开源软件的积极参与及贡献者。我们携手国内社区，企业，高校，及政府共创健康可持续发展的开源生态体系，并为中国开源软件和开源硬件的正确使用，授权许可，社区建设及治理，进行知识推广普及与提供相关服务。

url: "www.kaiyuanshe.cn"

# URL 路径前缀（不需要先导 "/"）
baseurl: ""

timezone: Asia/Shanghai
encoding: UTF-8

# 关闭安全限制，允许运行本地插件和 rb 文件
safe: off

theme: 

# 不使用 LSI 生成索引
lsi: false

# 不生成摘要信息
excerpt_separator: ""

markdown: kramdown
highlighter: rouge

sass:
    sass_dir: ./assets/scss
    style: compressed

defaults:
  - scope:
      type: posts
      path: ""
    values:
      layout: "post"
  - scope:
      type: raw
      path: ""
    values:
      layout: "raw"

# 忽略 source 下的这些文件/目录
# 以 _ 打头的目录也会被忽略
exclude:
  - Gemfile.lock

# ==== 本地预览设置 ====

host: 127.0.0.1
port: 4000
